name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install
        npm ci
        npm run build
        echo '{"version":"1.0.${{ github.run_number }}"}' > version.json
        tfx extension publish --manifest-globs azure-devops-extension.json src/**/*.json --overrides-file version.sjon --auth-type 'pat' --token '${{ secrets.MARKETPLACE_TOKEN }}'